apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: dequeue-to-es
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 10
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python39
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: dequeue_to_es.main
    packageref:
      name: dequeue-to-es
      namespace: ""
  requestsPerPod: 15
  resources: {}
