include:
- ./functions/sentiment_trends/__init__.py
- ./functions/sentiment_trends/sentiment_trends.py
- ./functions/sentiment_trends/requirements.txt
- ./functions/sentiment_trends/build.sh
kind: ArchiveUploadSpec
name: functions-sentiment-trends---init---py-zwbZ

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: sentiment-trends
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python39
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-sentiment-trends---init---py-zwbZ
status:
  buildstatus: pending
  lastUpdateTimestamp: "2025-05-20T08:21:35Z"
