include:
- ./addbdata.zip
kind: ArchiveUploadSpec
name: addbdata-zip-m5Ao

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: addbdata
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://addbdata-zip-m5Ao
status:
  buildstatus: pending
  lastUpdateTimestamp: "2025-05-19T01:38:29Z"
