apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: sentiment-trends-route
spec:
  createingress: false
  functionref:
    functionweights: null
    name: sentiment-trends
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /sentiment-trends/start/{start:[0-9]{4}-[0-1][0-9]-[0-3][0-9]}/end/{end:[0-9]{4}-[0-1][0-9]-[0-3][0-9]}/k/{k:[0-9]+}/platform/{platform:[a-zA-Z0-9_-]+}/index/{index:[a-zA-Z0-9_-]+}
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /sentiment-trends/start/{start:[0-9]{4}-[0-1][0-9]-[0-3][0-9]}/end/{end:[0-9]{4}-[0-1][0-9]-[0-3][0-9]}/k/{k:[0-9]+}/platform/{platform:[a-zA-Z0-9_-]+}/index/{index:[a-zA-Z0-9_-]+}
