apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: sentiment-diff-route
spec:
  createingress: false
  functionref:
    functionweights: null
    name: sentiment-diff
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /sentiment-diff/platform/{platform:[a-zA-Z0-9_-]+}/index/{index:[a-zA-Z0-9_-]+}
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /sentiment-diff/platform/{platform:[a-zA-Z0-9_-]+}/index/{index:[a-zA-Z0-9_-]+}
