apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: past-bluesky
spec:
  createingress: true
  functionref:
    functionweights: null
    name: past-bluesky
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /past-bluesky
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /past-bluesky
